/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author studente
 */
public class abb1 extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer abb1
     */
    public abb1() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donna = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        uomo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        donna.setBackground(new java.awt.Color(204, 204, 255));
        donna.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        donna.setText("DONNA");
        donna.setBorderPainted(false);
        donna.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        donna.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        donna.setMargin(new java.awt.Insets(1, 7, 1, 7));
        donna.setPreferredSize(new java.awt.Dimension(23, 375));
        donna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donnaMouseClicked(evt);
            }
        });
        donna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donnaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        uomo.setBackground(new java.awt.Color(204, 255, 204));
        uomo.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        uomo.setText("UOMO");
        uomo.setBorderPainted(false);
        uomo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        uomo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uomo.setMargin(new java.awt.Insets(1, 7, 1, 7));
        uomo.setPreferredSize(new java.awt.Dimension(23, 375));
        uomo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uomoMouseClicked(evt);
            }
        });
        uomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uomoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donna, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uomo, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(uomo, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donna, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donnaActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_donnaActionPerformed

    private void donnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donnaMouseClicked
        // TODO add your handling code here:
        DONNA d = new DONNA();
    }//GEN-LAST:event_donnaMouseClicked

    private void uomoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uomoMouseClicked
        // TODO add your handling code here:
        UOMO u = new UOMO();
    }//GEN-LAST:event_uomoMouseClicked

    private void uomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uomoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uomoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton uomo;
    // End of variables declaration//GEN-END:variables
}
