/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author studente
 */
public class UOMO extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer UOMO
     */
    public UOMO() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton14 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        vestitiscarpeaccessori = new javax.swing.JTabbedPane();
        maglietteepantaloni = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        calvinkleinblu = new javax.swing.JToggleButton();
        polobianca = new javax.swing.JToggleButton();
        felpabitmojiverde = new javax.swing.JToggleButton();
        magliaf1 = new javax.swing.JToggleButton();
        pologrigia = new javax.swing.JToggleButton();
        maglioncinonero = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jeansblu = new javax.swing.JToggleButton();
        pantagrigielegqanti = new javax.swing.JToggleButton();
        pantaloncini = new javax.swing.JToggleButton();
        pantatuta = new javax.swing.JToggleButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        nikebianche = new javax.swing.JToggleButton();
        nikenereebianche = new javax.swing.JToggleButton();
        stivalettimarroni = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cappellinivisiera = new javax.swing.JToggleButton();
        cappellinoneve = new javax.swing.JToggleButton();
        occhialisole = new javax.swing.JToggleButton();
        occhialivista = new javax.swing.JToggleButton();

        jToggleButton14.setText("jToggleButton14");

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        vestitiscarpeaccessori.setBackground(new java.awt.Color(255, 204, 0));
        vestitiscarpeaccessori.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N

        maglietteepantaloni.setBackground(new java.awt.Color(153, 0, 153));
        maglietteepantaloni.setForeground(new java.awt.Color(255, 255, 255));
        maglietteepantaloni.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N

        calvinkleinblu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcvinmagliablu.PNG"))); // NOI18N

        polobianca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camiciabianca.PNG"))); // NOI18N

        felpabitmojiverde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/felpaverde.PNG"))); // NOI18N

        magliaf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magliaformula1_maschio.PNG"))); // NOI18N

        pologrigia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pologrigia.PNG"))); // NOI18N

        maglioncinonero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maglioncinocolloaltanero.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calvinkleinblu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(felpabitmojiverde, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(maglioncinonero, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(polobianca, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(magliaf1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pologrigia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(polobianca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calvinkleinblu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(felpabitmojiverde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maglioncinonero, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(magliaf1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(pologrigia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        maglietteepantaloni.addTab("Magliette", jPanel3);

        jeansblu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantablu.PNG"))); // NOI18N
        jeansblu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jeansbluMouseClicked(evt);
            }
        });

        pantagrigielegqanti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantaeleganti.PNG"))); // NOI18N
        pantagrigielegqanti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pantagrigielegqantiMouseClicked(evt);
            }
        });

        pantaloncini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantaloncinirossi.PNG"))); // NOI18N
        pantaloncini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pantalonciniMouseClicked(evt);
            }
        });

        pantatuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tutajordangrigio.PNG"))); // NOI18N
        pantatuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pantatutaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jeansblu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pantaloncini, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pantagrigielegqanti, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(pantatuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pantagrigielegqanti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jeansblu, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pantaloncini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pantatuta, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)))
        );

        maglietteepantaloni.addTab("Pantaloni", jPanel4);

        vestitiscarpeaccessori.addTab("VESTITI", maglietteepantaloni);

        nikebianche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nikebinache.PNG"))); // NOI18N

        nikenereebianche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scarpenike.PNG"))); // NOI18N

        stivalettimarroni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stivaletto.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nikebianche, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stivalettimarroni, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nikenereebianche, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nikebianche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stivalettimarroni, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nikenereebianche, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("                                                                                                                                       ", jPanel5);

        vestitiscarpeaccessori.addTab("SCARPE", jTabbedPane3);

        cappellinivisiera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berrettogrigio.PNG"))); // NOI18N

        cappellinoneve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cappellinoneve.PNG"))); // NOI18N

        occhialisole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/occhilidasole.PNG"))); // NOI18N

        occhialivista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/occhilidavista.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(occhialisole, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(occhialivista, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(cappellinivisiera, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cappellinoneve, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cappellinoneve, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(cappellinivisiera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(occhialisole, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(occhialivista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 392, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        vestitiscarpeaccessori.addTab("ACCESSORI", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vestitiscarpeaccessori, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vestitiscarpeaccessori)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jeansbluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeansbluMouseClicked
        // TODO add your handling code here:
        /*button = new Button ("pantablu.PNG");
        button.addActionListener (new ButtonClickListener());
        add(button, BorderLAyout.SOUTH);
        public void actionPerformed (ActionEvent e){
        manichino manichino = new manichino("D:\VESTITI\UOMO RIDIM\pantablu.PNG")
/*etichettamanichino*/ //JLabel imageLabel = new JLabel(manichino);
/*panel.add(imageLabel);
panel.revalidate();
panel.repaint();
}*/
    }//GEN-LAST:event_jeansbluMouseClicked

    private void pantagrigielegqantiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantagrigielegqantiMouseClicked
        // TODO add your handling code here:
/*button = new Button ("pantaeleganti.PNG");
        button.addActionListener (new ButtonClickListener());
        add(button, BorderLAyout.SOUTH);
        public void actionPerformed (ActionEvent e){
        manichino manichino = new manichino("D:\VESTITI\UOMO RIDIM\pantaeleganti.PNG")
/*etichettamanichino*/ //JLabel imageLabel = new JLabel(manichino);
/*panel.add(imageLabel);
panel.revalidate();
panel.repaint();
}*/
    }//GEN-LAST:event_pantagrigielegqantiMouseClicked

    private void pantalonciniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantalonciniMouseClicked
        // TODO add your handling code here:
/*button = new Button ("pantaloncinirossi.PNG");
        button.addActionListener (new ButtonClickListener());
        add(button, BorderLAyout.SOUTH);
        
        manichino manichino = new manichino("D:\VESTITI\UOMO RIDIM\pantaloncinirossi.PNG")
/*etichettamanichino*/ //JLabel imageLabel = new JLabel(manichino);
/*panel.add(imageLabel);
panel.revalidate();
panel.repaint();
}*/
    }//GEN-LAST:event_pantalonciniMouseClicked
/*
    private void pantatutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantatutaMouseClicked
        // TODO add your handling code here:
//button = new Button ("tutajordangrigio.PNG");
     
        
        //manichino manichino = new manichino("D:\\VESTITI\\UOMO RIDIM\\tutajordangrigio.PNG")
///*etichettamanichino*/ //JLabel imageLabel = new JLabel(manichino); 
/*jPanel6.add(imageLabel);
jPanel6.revalidate();
jPanel6.repaint();
}
    }//GEN-LAST:event_pantatutaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton calvinkleinblu;
    private javax.swing.JToggleButton cappellinivisiera;
    private javax.swing.JToggleButton cappellinoneve;
    private javax.swing.JToggleButton felpabitmojiverde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JToggleButton jToggleButton14;
    public javax.swing.JToggleButton jeansblu;
    private javax.swing.JToggleButton magliaf1;
    private javax.swing.JTabbedPane maglietteepantaloni;
    private javax.swing.JToggleButton maglioncinonero;
    private javax.swing.JToggleButton nikebianche;
    private javax.swing.JToggleButton nikenereebianche;
    private javax.swing.JToggleButton occhialisole;
    private javax.swing.JToggleButton occhialivista;
    private javax.swing.JToggleButton pantagrigielegqanti;
    private javax.swing.JToggleButton pantaloncini;
    private javax.swing.JToggleButton pantatuta;
    private javax.swing.JToggleButton polobianca;
    private javax.swing.JToggleButton pologrigia;
    private javax.swing.JToggleButton stivalettimarroni;
    private javax.swing.JTabbedPane vestitiscarpeaccessori;
    // End of variables declaration//GEN-END:variables
*/